### ISSUE TITLE
Smart Contract and Front end values don't match?

### ISSUE THREAD

**Issue by OmJao** [stevenstc/SMART-SITE-CAPITAL#2]
Hi Steven,

I hope you are all OK with this pandemic situation.

I have a  confusing issue to understand and sorry to ask many questions, but there's no better person to ask than the coder himself.

Here's the issue:
 
The active Smart Contract  SiteCapital (TTXotPkx5YypmMjgzvGb9496XmrCxbNNaZ) values:
 
11.dias
Call
root:"165"

14.porcent
Call
root:"125"
 
---------------------------------------------
The main deposit code lines (126-134) at:
 
 https://github.com/stevenstc/SMART-SITE-CAPITAL/blob/main/src/components/CrowdFunding/index.js
 
 var dias = 185;//await Utils.contract.tiempo().call();

    //var velocidad = await Utils.contract.velocidad().call();

    //dias = (parseInt(dias)/86400)*velocidad;

var porcentaje = 155;//await Utils.contract.porcent().call();

---------------------------------------------

On the website (https://smartsitecapital.ml) these are the published values:

TASA E.A 108.51%
RETORNO TOTAL 155%
RECOMPENSA 55%
Tiempo en días 185
---------------------------------------------------------

I thought the  Smart Contract (TTXotPkx5YypmMjgzvGb9496XmrCxbNNaZ) can not be altered and is responsible to execute its own values.

So if I want to use the same logic and pass my own values from the Deposit form on the website,
what values can I use to achieve a simple deposit:

365 days deposit
!23% Per Year

I understand the 'RETORNO TOTAL 155%' but don't understand the workings of:

TASA E.A 108.51%
RECOMPENSA 55%

Is this like a compounding interest percentage calculation?

Can you please describe why there are different percentages like 
TASA E.A 108.51%
RETORNO TOTAL 155%
RECOMPENSA 55%

Many thanks for all your contribution and guidance on Tron development and congratulations on your Super Representative achievement :)

Best regards,

**Comment by stevenstc** [comment]
That is correct since it was requested by the company that paid for the development, there is no problem since this was intentional
